const allCategories = {
  Fluency: {
    "Clarity (low)": "You are working towards expressing your ideas with greater clarity.",
    "Speed (slow)":"Your pace of speech is developing and sounding more natural.",
    "Stress / Intonation (starting)": "You are starting to use natural-sounding stresses and intonation while speaking.",
    "Stress / Intonation (developing)": "You are working well towards using natural-sounding stresses and intonation while speaking.",
    "Stress / Intonation (improving)": "You are making good progress in terms of incorporating natural-sounding speech stresses and intonation.",
    "Stress / Intonation (mastering)": "You use stresses and intonation to convey meaning in a very natural-sounding way, which is essential for mastery of spoken English."
  },
  Grammar: {
    "after then...": "Consider changing: [after then] to either: [after that] or [then], as these are more common and grammatically sound expressions.",
    "article - missing": "Check for missing articles (a, an, the) in your sentences to keep them smooth and avoid fragmentation.",
    "article -  wrong choice ('a' or 'an')": "'A' is used before consonant sounds and 'an' before vowel sounds.",
    "article - wrong choice ('a/an' or 'the')": "Take care when choosing the most appropriate article from: [a, an, or the]. Use [a / an] for an  unspecified noun. Use [the] for a specified noun.",
    "article - with proper noun in error": "Note that [the] is not usually used before proper nouns.",
    "article - with uncountable noun in error": "Uncountable nouns generally don't take 'a' or 'an'.",
    "adjectives - muddled": "Take care when choosing the most appropriate adjective, for example: [bored / boring, nervous / nerve-racking, scared / scary, tired / tiring, etc.]",
    "can't / couldn't": "Take care when choosing from [can't] and [couldn't]. Match the tense.",
    "don't / doesn't": "Take care when choosing from [don't] and [doesn't].",
    "furnitures, homeworks": "Category-type nouns are uncountable, for example: []. No need for the 's' at the end.",
    "German / Germany": "Note that [German] is the language and nationality, and [Germany] is the country name. Easily muddled.",
    "in case of / in the case of": "Use `in case of` for potential events or precautions.\nUse `in the case of` for a specific person, thing, or situation",
    "is / are": "Take care when choosing from [is] and [are]. Use [is] for singular nouns, and [are] for plural nouns.",
    "is / was": "Take care when choosing from [is] and [was]. Use [is] for the present tense, and [was] for the past tense.",
    "mixed phrases": "Take care to avoid blending two or more very common phrases as this can sound a little peculiar. Aim to choose one or the other.",
    "much / many": "Take care when choosing from [much] and [many] as these are easily muddled. Use [much] for uncountable nouns, and [many] for countable nouns.",
    "noodle / noodles": "Always add an S at the end of the word [noodles] unless it forms part of an adjective such as: [noodle-bar, noodle-cafe, noodle-dish]. If in doubt, place an S, for example: [I ate noodles. / Noodles are scrumptious!]",
    "noun number error": "Add an S at the end of countable plural nouns for grammatical correctness and clarity. Common errors here occur on words like [hour(s), year(s) etc. For example:\n•1 hour / 2 hours\n•1 year / many years",
    "other / another": "Use [other] for plural or non-count nouns (e.g., 'other chairs', 'other information').\n\nUse [another] for a single, unspecified, countable noun (e.g., 'another chair')",
    "prepositions (in, on, at)": "Check the prepositions: [in, on, & at]. Practice using these in different sentences as often as possible.",
    "so / such": "Take care when choosing from: [so] and [such]. Both have a similar purposes but require a different sentence structure. For example: [It was SO cloudy today. // It was SUCH a cloudy day.]",
    "some / a": "Use `some` for plural forms. Use `a / an / the` for singular forms.\n\n(That said, we can say: [some kind of... / some sort of...] when referring to singular forms.",
    "to / for": "Choosing between [to] and [for] can be tricky, but you will get there with continued checking and practice.",
    "Two weeks later...": `When talking about future, consider using:\n• [in three minutes]\n• [in three minute's time]\n\ninstead of [three minutes later].\n\nUse [later] if the exact future time is not specified.`,
    "until / before": "Take care when choosing from [until] or [before or by]. Both have similar uses, but different sentence structures. Here are some examples of usage:\n• I have to finish this report BY tomorrow.\n• I have to finish this report BEFORE tomorrow.\n• I have UNTIL tomorrow to finish this report.",
    "Verb Tense Error": "Check the verb form in some cases to ensure that it aligns correctly with the past, present, or future tense.",
    "Subject Verb Agreement": "Check that the subject and verb are in agreement.",
    "Tense Consistency": "Ensure the tense stays consistent throughout.",
    "Word Order": "Your vocabulary choices were excellent. In some cases, however, consider re-ordering the words in your sentence for extra clarity."
  },
  Pronunciation: {
    "Energy, Technology": "Check and practice the [gy] (or JEE) sound at the end of words like: [energy, biology, technology, etc.]. Keep the sound strong and clear.",
    "F Sounds": "Check and practice the F sound in words like: []",
    "height": "Take care when pronouncing [height]. It has a similar spelling to [weight] but pronounced differently. Check and practice this one.",
    "L Sounds": "Check and practice the L sound in words like: []",
    "Quiet, Quite, Quit": "Note the subtle differences between [quiet, quite, and quit]. They look very similar, but have different meanings and slightly different pronunciation forms.",
    "language": "Check and practice the GWIJ sound in words like: [language]. It's a rare sound, but a common word, so mastery is essential.",
    "R Sounds": "Check and practice the R sound in words like: []",
    "R & L Sounds": "Practice alternating R and L sounds clearly, for example: []",
    "SQU Sounds": "Check and practice the SQU (or SKW sound) in words like: []",
    "Syllable Stress Error": "Change the syllable stress in some instances for improved clarity.",
    "Tail Sounds": "You are working towards avoiding the extra unwanted syllable sounds at the end of some words, like: [finished, searched, watched, etc.] Aim for one long syllable, rather than breaking the word into two syllables.",
    "TH Sounds": "Aim to keep your TH sounds clear and sharp for a more academic and business-like tone. This is especially important when we are speaking slowly and clearly.",
    "W Sounds": "Check and practice the W sound in words like: [would, woman, someone, etc.]",
    "Z Sounds": "Check and practice the Z sound in words like: [zero, zombie, exhausted, etc.]",
  },
  Self_Correction: {
    "Grammar - Mastering": "You are mastering the art of quick and discreet self-corrections of grammar, as a native-English speaker would. This is excellent to hear.",
  "Grammar - Improving": "Your skill in picking-up and self-correcting grammar is developing fast. This is really good to hear.",
  "Grammar - Beginning": "You are beginning to notice and self-correct grammar slips, which is great skill to practice in our class.",
    "Pronunciation - Mastering": "You are mastering the art of quick and discreet self-corrections of pronunciation. This is excellent to hear.",
  "Pronunciation - Improving": "Your skill in picking-up and self-correcting pronunciation is developing fast. This is really good to hear.",
  "Pronunciation - Beginning": "You are beginning to notice and self-correct pronunciation slips, which is great skill to practice in our class."
  },
  Admin: {
    "2x10min combined classes": "2 x 10-minute classes combined. Notes on previous class page.",
    "2x20min combined classes": "2 x 20-minute classes combined. Notes on previous class page.",
    "Student Late": "The student answered after the class start time.",
    "Student Absent (7/8)": "Absent 7 of 8. I will report next class if tagged absent or cancelled."
  }
};